baseURL = 'https://reformationparish.com/'
languageCode = 'en-us'
title = 'Reformation Parish'
theme = 'reformation'

[params]
  description = 'A confessional, liturgical church in the Communion of Reformed Evangelical Churches'
  tagline = 'On Earth as it is in Heaven'
  location = 'Senoia, GA'
  mailingAddress = '1741-2 Newnan Crossing Blvd E Newnan, GA 30265'
  meetingAddress = '1225 Eastside School Rd, Senoia, GA 30276'
  # phone = '(555) 000-0000'
  # email = 'info@reformationparish.com'
  serviceDay = 'Sunday'
  serviceTime = '10:30 AM'
  denomination = 'Communion of Reformed Evangelical Churches'

[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 10

[[menus.main]]
  name = 'Worship'
  url = '/worship/'
  weight = 20

[[menus.main]]
  name = 'Sermons'
  url = '/sermons/'
  weight = 30

[[menus.main]]
  name = 'Church Center'
  url = 'https://reformationparish.churchcenter.com'
  weight = 40

[[menus.footer]]
  name = 'About'
  url = '/about/'
  weight = 10

[[menus.footer]]
  name = 'Worship'
  url = '/worship/'
  weight = 20

[[menus.footer]]
  name = 'Sermons'
  url = '/sermons/'
  weight = 30

[[menus.footer]]
  name = 'Church Center'
  url = 'https://reformationparish.churchcenter.com'
  weight = 40
